version: '3'
services:
  app:
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    build: .
    ports:
      - 8080:8080
    links:
      - db:redis
  db:
    image: redis:alpine
    hostname: redis
    command: redis-server --appendonly yes --save 60 100
    volumes:
      - $PWD/redis-data:/data
    ports:
      - 6379:6379

